version: "3.8"

services:
  backend:
    build: .
    container_name: media-app
    ports:
      - "5000:5000"
    env_file:
      - .env.docker
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo-data:
